applications:
- application_name: web-asset3
  auth_header_name: name
  auth_header_value: encrypted$AQICAHi84flUOGUkbkZkTL0gAmiUV15UwsdMGpTcuhhcwetrxgFR1j44VoDhjludTjasifsuAAAAYzBhBgkqhkiG9w0BBwagVDBSAgEAME0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdC+gaJNV+1TuL9n/AgEQgCDWBq7tdlpW9QjsS4gKcj54fO0cJr7yrrRapNf8W65KYQ==
  authentication_mode: selenium
  exclude_paths:
  - .*logout.*
  - .*lior.*
  login_page_url: https://platform.mydomain.com/login
  password: encrypted$AQICAHi84flUOGUkbkZkTL0gAmiUV15UwsdMGpTcuhhcwetrxgHw0ke5h7khkgHv5HdQvHGRAAAAYTBfBgkqhkiG9w0BBwagUjBQAgEAMEsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH13vcAGT+hwgHQvMAgEQgB7IxbJbGyUHF1oAvYsytnS5qr4A+1GJlSeaDTJHaxY=
  password_css_selector: '[key=val2]'
  target_url: https://platform.mydomain.com
  type: web
  username: user1
  username_css_selector: '[key=value]'
- api_domain: api.mydomaain.com
  application_name: api-asset3
  auth_header_name: Authorization
  auth_header_value: encrypted$AQICAHi84flUOGUkbkZkTL0gAmiUV15UwsdMGpTcuhhcwetrxgFo26VvbSPvhtTHH+6e1jdZAAAF9jCCBfIGCSqGSIb3DQEHBqCCBeMwggXfAgEAMIIF2AYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzSE6muJ05ZzJVNZw0CARCAggWp4PCR4Se9f0fNse9m4fSajF9ylC4RdeAgLQ3r2w9b0hCXRylmzmw7WquOp
  authentication_mode: header
  exclude_paths:
  - .*logout.*
  target_url: https://api.bucket.s3.amazonaws.com/openapi.json
  type: api
